if (!require("devtools")) install.packages("devtools")
if (!require("bitops")) install.packages("bitops")
if (!require("RCurl")) install.packages("RCurl")
if (!require("stringi")) install.packages("stringi")
if (!require("httr")) install.packages("httr")
if (!require("swirl")) install.packages("swirl")
if (!require("swirlify")) install.packages("swirlify")
#install.packages("devtools", "bitops", "RCurl", "stringi", "httr", "swirl")
library(devtools)
library(bitops)
library(RCurl)
library(httr)
library(swirl)
library(swirlify)
set_config( config( ssl_verifypeer = 0L ) )
if (file.exists("/opt/R/home/library/aprendeR/Fundamentos")) {
  uninstall_course("Fundamentos")
  }
install_course_github('Rafael-Resendiz','Fundamentos')
select_language(language = "spanish")
